add braintree monthly subscription
10clouds/ecommerce pull request #14
Opened 2016-11-28 00:22 UTC by inlanger

2016-11-28 08:39 UTC, CrowbarKZ commented on ecommerce/extensions/payment/processors/braintree.py
> +        customer_id = "{}".format(user.id)
this looks like a case for `str(user.id)`. what type is `user.id` originally?

2016-11-28 08:41 UTC, CrowbarKZ commented on ecommerce/extensions/payment/processors/braintree.py
> +        customer = self.get_or_create_customer(user)
`customer` is assigned but not used, could be just `self.get_or_create_customer(user)`

2016-11-28 08:42 UTC, CrowbarKZ commented on ecommerce/extensions/payment/processors/braintree.py
> +        customer_id = "{}".format(customer.id)
again looks like a case for `str(customer.id)`

2016-11-28 08:46 UTC, CrowbarKZ commented on ecommerce/extensions/payment/processors/braintree.py
> +
minor: this empty line makes it a bit confusing, like the `try` and `except` blocks are some separate blocks. At least to me :)

2016-11-28 08:48 UTC, CrowbarKZ commented on ecommerce/extensions/payment/processors/braintree.py
> +            'plan_id': 'edevate_subscription'
is it some constant id on the brain tree side? if so might be we should create a constant for it in settings

2016-11-28 08:49 UTC, CrowbarKZ requested changes
some notes

2016-11-28 11:17 UTC, aniav commented on ecommerce/extensions/payment/processors/braintree.py
> +        customer_id = "{}".format(user.id)
You don't need to use `str()` on anything using `format()`, it will do the casting by itself if the value is something as simple as an int.

2016-11-28 11:55 UTC, aniav approved these changes

2016-11-28 13:06 UTC, CrowbarKZ commented on ecommerce/extensions/payment/processors/braintree.py
> +        customer_id = "{}".format(user.id)
i mean `customer_id = str(user.id)`

2016-11-29 10:06 UTC, inlanger commented
@CrowbarKZ I've made PR fixes, please check

2016-11-29 17:37 UTC, CrowbarKZ approved these changes

2016-12-06 12:20 UTC, merged